openapi: 3.0.0
info:
  title: Job Track API's
  version: 1.0.0
paths:
  /api/job/track:
    post:
      summary: Job Track API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobTrackRequestBody'
              type: object
              properties:
                email:
                  type: string
                  example: ''
                accessToken:
                  type: string
                  example: ''
                expiryDate:
                  type: string
                  example: ''
                refreshToken:
                  type: string
                  example: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobTrackSuccessResponse'
              example:
                [
                  {
                    'id': '18492dfa83f8bf38',
                    'date': '2023-11-03T01:44:18.000Z',
                    'company': 'BASF',
                    'position': 'Internship Web Development',
                    'status': 'Application Received',
                    'email': 'mahesh.nidugala@gmail.com',
                  },
                  {
                    'id': '18592df8eb643884ef',
                    'date': '2023-11-03T01:41:18.000Z',
                    'company': 'BASF',
                    'position': 'Internship Web Development (m/f/d) at BASF SE',
                    'status': 'Application received',
                    'email': 'mahesh.nidugala@gmail.com',
                  },
                ]
        '400':
          description: BAD REQUEST
          content:
            application/json:
              example:
                {
                  'timestamp': '2024-01-29T17:31:22.228Z',
                  'status': 400,
                  'error': 'Bad Request',
                  'message':
                    [
                      { 'msg': 'Invalid value', 'param': 'email', 'location': 'body' },
                      { 'msg': 'Valid email is required.', 'param': 'email', 'location': 'body' },
                    ],
                  'path': '/api/job/track',
                }
        '500':
          description: INTERNAL SERVER ERROR
          content:
            application/json:
              example:
                {
                  'timestamp': '2024-01-17T02:40:35.512Z',
                  'status': 500,
                  'error': 'Internal Server Error',
                  'message': 'Some Error Message',
                  'path': '/api/job/track',
                }
components:
  schemas:
    JobTrackRequestBody:
      type: object
      properties:
        email:
          type: string
        accessToken:
          type: string
        expiryDate:
          type: string
        refreshToken:
          type: string
    JobTrackSuccessResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
          date:
            type: string
          company:
            type: string
          position:
            type: string
          status:
            type: string
          email:
            type: string
